apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: devops-app
          image: 3.108.66.213:8000/devops-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
